In [1]:
import sys

sys.path.append('/Users/aady/Desktop/Ayush Vats/ETL Pipeline Project/etl')

from extract import get_amazon_data

df = get_amazon_data()

# Remove Duplicates

df = df.drop_duplicates()

df_backup = df

/Users/aady/Desktop/Ayush Vats/ETL Pipeline Project/etl/extract.py:18: DtypeWarning: Columns (0: Unnamed: 22) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path)

In [2]:
# Standarize column name

df.columns = df.columns.str.replace(' ','_')
df.columns = df.columns.str.replace('-','_')

df.columns = df.columns.str.lower()
df.columns = df.columns.str.rstrip('_')
df.columns = df.columns.str.replace(' ','_')

df.head()

,index,order_id,date,status,fulfilment,sales_channel,ship_service_level,style,sku,category,...,currency,amount,ship_city,ship_state,ship_postal_code,ship_country,promotion_ids,b2b,fulfilled_by,unnamed:_22
0,0,405-8078784-5731545,04-30-22,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,...,INR,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,NaN,False,Easy Ship,NaN
1,1,171-9198151-1101146,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,...,INR,406.00,BENGALURU,KARNATAKA,560085.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,NaN
2,2,404-0687676-7273146,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,...,INR,329.00,NAVI MUMBAI,MAHARASHTRA,410210.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,True,NaN,NaN
3,3,403-9615377-8133951,04-30-22,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,...,INR,753.33,PUDUCHERRY,PUDUCHERRY,605008.0,IN,NaN,False,Easy Ship,NaN
4,4,407-1069790-7240320,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,...,INR,574.00,CHENNAI,TAMIL NADU,600073.0,IN,NaN,False,NaN,NaN

In [ ]:
# import pandas as pd

# location = '/Users/aady/Desktop/Ayush Vats/ETL Pipeline Project/data'
# df_amazon = df[['index','order_id','date','status','sales_channel','amount']]
# df_amazon.to_csv(location + '/amazon_main')

,index,order_id,date,status,sales_channel,amount
0,0,405-8078784-5731545,04-30-22,Cancelled,Amazon.in,647.62
1,1,171-9198151-1101146,04-30-22,Shipped - Delivered to Buyer,Amazon.in,406.00
2,2,404-0687676-7273146,04-30-22,Shipped,Amazon.in,329.00
3,3,403-9615377-8133951,04-30-22,Cancelled,Amazon.in,753.33
4,4,407-1069790-7240320,04-30-22,Shipped,Amazon.in,574.00
...,...,...,...,...,...,...
128970,128970,406-6001380-7673107,05-31-22,Shipped,Amazon.in,517.00
128971,128971,402-9551604-7544318,05-31-22,Shipped,Amazon.in,999.00
128972,128972,407-9547469-3152358,05-31-22,Shipped,Amazon.in,690.00
128973,128973,402-6184140-0545956,05-31-22,Shipped,Amazon.in,1199.00
128974,128974,408-7436540-8728312,05-31-22,Shipped,Amazon.in,696.00

In [3]:
# df['amount'].apply(lambda x : x<0 : x*=-1)

df['amount'] = df['amount'].apply(lambda x: abs(x))
df.head()

,index,order_id,date,status,fulfilment,sales_channel,ship_service_level,style,sku,category,...,currency,amount,ship_city,ship_state,ship_postal_code,ship_country,promotion_ids,b2b,fulfilled_by,unnamed:_22
0,0,405-8078784-5731545,04-30-22,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,...,INR,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,NaN,False,Easy Ship,NaN
1,1,171-9198151-1101146,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,...,INR,406.00,BENGALURU,KARNATAKA,560085.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,NaN
2,2,404-0687676-7273146,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,...,INR,329.00,NAVI MUMBAI,MAHARASHTRA,410210.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,True,NaN,NaN
3,3,403-9615377-8133951,04-30-22,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,...,INR,753.33,PUDUCHERRY,PUDUCHERRY,605008.0,IN,NaN,False,Easy Ship,NaN
4,4,407-1069790-7240320,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,...,INR,574.00,CHENNAI,TAMIL NADU,600073.0,IN,NaN,False,NaN,NaN

In [4]:
df.shape

(128975, 24)

In [5]:
# location = '/Users/aady/Desktop/Ayush Vats/ETL Pipeline Project/data/cleaned'
# df.to_csv(location + '/cleaned.csv')

# print("Saved cleaned csv file in data/cleaned")

In [6]:
# location = '/Users/aady/Desktop/Ayush Vats/ETL Pipeline Project/data/cleaned'
# df.to_excel(location + '/cleaned.xlsx')

In [7]:
import pandas as pd
import psycopg2 as pg2

pg2.connect(database = 'test', user = 'postgres', password = 'aady_02')

OperationalError: connection to server on socket "/tmp/.s.PGSQL.5432" failed: FATAL:  database "test" does not exist

In [6]:
# import sys
# sys.path.append('/Users/aady/Desktop/Ayush Vats/ETL Pipeline Project/data/raw')

import pandas as pd

df_amazon = pd.read_csv('/Users/aady/Desktop/Ayush Vats/ETL Pipeline Project/data/raw/Amazon Sale Report.csv')

df_amazon.head()

/var/folders/jh/7d3zkbt12k76jb3h3twj7s4w0000gn/T/ipykernel_14420/3599346618.py:6: DtypeWarning: Columns (0: Unnamed: 22) have mixed types. Specify dtype option on import or set low_memory=False.
  df_amazon = pd.read_csv('/Users/aady/Desktop/Ayush Vats/ETL Pipeline Project/data/raw/Amazon Sale Report.csv')

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,...,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Unnamed: 22
0,0,405-8078784-5731545,04-30-22,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,...,INR,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,NaN,False,Easy Ship,NaN
1,1,171-9198151-1101146,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,...,INR,406.00,BENGALURU,KARNATAKA,560085.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,NaN
2,2,404-0687676-7273146,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,...,INR,329.00,NAVI MUMBAI,MAHARASHTRA,410210.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,True,NaN,NaN
3,3,403-9615377-8133951,04-30-22,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,...,INR,753.33,PUDUCHERRY,PUDUCHERRY,605008.0,IN,NaN,False,Easy Ship,NaN
4,4,407-1069790-7240320,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,...,INR,574.00,CHENNAI,TAMIL NADU,600073.0,IN,NaN,False,NaN,NaN

In [ ]:
df.columns

Index(['index', 'order_id', 'date', 'status', 'fulfilment', 'sales_channel',
       'ship_service_level', 'style', 'sku', 'category', 'size', 'asin',
       'courier_status', 'qty', 'currency', 'amount', 'ship_city',
       'ship_state', 'ship_postal_code', 'ship_country', 'promotion_ids',
       'b2b', 'fulfilled_by', 'unnamed:_22'],
      dtype='str')

In [ ]:
df_sales = pd.read_csv('/Users/aady/Desktop/Ayush Vats/ETL Pipeline Project/data/raw/Sale Report.csv')
df_sales = df_sales.set_index(keys = 'order_id')

KeyError: "None of ['order_id'] are in the columns"

In [14]:
for i in range(0,df_sales.shape[1]):
    print(df_sales.columns[i], df_sales.iloc[:,i].isna().sum())
    print(df_sales.columns[i] , df_sales.iloc[:,i].nunique())
    print("")
print(df_sales['index'].nunique())

index 0
index 9271

SKU Code 83
SKU Code 9170

Design No. 36
Design No. 1594

Stock 36
Stock 295

Category 45
Category 21

Size 36
Size 11

Color 45
Color 62

9271

In [ ]:
for i in range(0,df_amazon.shape[1]):
    print(df_amazon.columns[i] , df_amazon.iloc[:,i].isna().sum())

index 0
Order ID 0
Date 0
Status 0
Fulfilment 0
Sales Channel  0
ship-service-level 0
Style 0
SKU 0
Category 0
Size 0
ASIN 0
Courier Status 6872
Qty 0
currency 7795
Amount 7795
ship-city 33
ship-state 33
ship-postal-code 33
ship-country 33
promotion-ids 49153
B2B 0
fulfilled-by 89698
Unnamed: 22 49050